### ISSUE TITLE
Add install case when users don't have any workflows

### ISSUE THREAD

**Issue by miguelsolorio** [SamVerschueren/alfred-link#21]
Originally from https://github.com/jonrohan/alfred-figma/issues/1

Tried to install a workflow (that uses alfred-link) via the cli `npm install --global alfred-figma` but kept getting this error:

```
> alfred-figma@0.2.0 postinstall /Users/misolori/.nvm/versions/node/v8.9.4/lib/node_modules/alfred-figma
> alfy-init

{ Error: Command failed: alfred-link
Error: Workflow directory `/Users/misolori/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows` does not exist
    at pathExists.then.exists (/Users/misolori/.nvm/versions/node/v8.9.4/lib/node_modules/alfred-figma/node_modules/alfred-link/index.js:19:10)
    at <anonymous>


    at Promise.all.then.arr (/Users/misolori/.nvm/versions/node/v8.9.4/lib/node_modules/alfred-figma/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Workflow directory `/Users/misolori/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows` does not exist\n    at pathExists.then.exists (/Users/misolori/.nvm/versions/node/v8.9.4/lib/node_modules/alfred-figma/node_modules/alfred-link/index.js:19:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-figma@0.2.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfred-figma@0.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/misolori/.npm/_logs/2018-10-25T15_46_44_571Z-debug.log
```

Turns out that if you don't have any workflows installed there is no workflows directory in `Alfred.alfredpreferences`. This case should be added during install to avoid these errors.

**Comment by megaroeny** [comment]
Still having this issue, and trying to install the same exact workflow. My issue is probably because I have my Alfred preferences in my Dropbox folder (not the default). So I wouldn't consider this issue closed: https://github.com/SamVerschueren/alfred-link/pull/20#issuecomment-472024948
